// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOW3fteFoN9QjuadSS7Hsja-UbiaSDHCU',
    appId: '1:520067816724:web:e431bb096c54a0db257601',
    messagingSenderId: '520067816724',
    projectId: 'chronoapp-416305',
    authDomain: 'chronoapp-416305.firebaseapp.com',
    storageBucket: 'chronoapp-416305.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9uS-Dyr20_U4v431gBSh5_ujK4WYLKVs',
    appId: '1:520067816724:android:43feb284d4e7adec257601',
    messagingSenderId: '520067816724',
    projectId: 'chronoapp-416305',
    storageBucket: 'chronoapp-416305.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmC8vCksVKdt-VXLsJdRlhs7WrPRzPsqs',
    appId: '1:520067816724:ios:15ce0350a3980300257601',
    messagingSenderId: '520067816724',
    projectId: 'chronoapp-416305',
    storageBucket: 'chronoapp-416305.appspot.com',
    iosBundleId: 'com.example.cronoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmC8vCksVKdt-VXLsJdRlhs7WrPRzPsqs',
    appId: '1:520067816724:ios:f3923818e2ee3c0c257601',
    messagingSenderId: '520067816724',
    projectId: 'chronoapp-416305',
    storageBucket: 'chronoapp-416305.appspot.com',
    iosBundleId: 'com.example.cronoapp.RunnerTests',
  );
}
