name: cronoapp
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  animate_do: ^4.2.0
  audioplayers: ^6.0.0
  change_app_package_name: ^1.1.0
  circular_countdown_timer: ^0.2.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.4.3
  flutter_speed_dial: ^7.0.0
  go_router: ^11.1.4
  path: ^1.9.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/icon/
